### ISSUE TITLE
[DOC] Missing `config` setup for `range_client`

### ISSUE THREAD

**Issue by FrancisMurilloDigix** [thiamsantos/pwned#1]
Hi, thanks for the library. 

Just wanted to note that in order to get the library to work, I needed to configure the range client:

```elixir
# config/dev.exs
config :pwned, range_client: Pwned.Range.HTTPClient

# config/test.exs
config :pwned, range_client: Pwned.Range.Sandbox
```

Perhaps the README should have a section indicating this?

**Comment by thiamsantos** [comment]
@FrancisMurilloDigix Yeah, you are absolutely right. I think a best path would be just make the HTTPClient the default client and make no additional changes necessary for the library to work.

**Comment by thiamsantos** [comment]
Fixed and published at https://hex.pm/packages/pwned/1.1.0. Thanks for the report @FrancisMurilloDigix .
